kind: 'BuildConfig'
apiVersion: 'v1'
metadata:
  name: 'internalorder-api'
  namespace: cicd
spec:
  source:
    git:
      ref: master
      uri: 'https://github.com/swapnalitoraskarttl/RepoTMCVInternalOrderInsertOrUpdate.git'
    sourceSecret:
      name: offtake-vme
  strategy:
    jenkinsPipelineStrategy:
      env:
      - name: PROJECT
        value: dev-esb
      jenkinsfilePath: 'Jenkinsfile'
