package com.siebel.asi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2020-03-02T11:14:13.086+05:30
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://siebel.com/asi/", name = "Default")
@XmlSeeAlso({com.siebel.xml.order_20interface.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Default {

    @WebMethod(operationName = "TMCVInternalOrderInsertOrUpdate", action = "document/http://siebel.com/asi/:TMCVInternalOrderInsertOrUpdate")
    @WebResult(name = "TMCVInternalOrderInsertOrUpdate_Output", targetNamespace = "http://siebel.com/asi/", partName = "TMCVInternalOrderInsertOrUpdate_Output")
    public TMCVInternalOrderInsertOrUpdateOutput tmcvInternalOrderInsertOrUpdate(
        @WebParam(partName = "TMCVInternalOrderInsertOrUpdate_Input", name = "TMCVInternalOrderInsertOrUpdate_Input", targetNamespace = "http://siebel.com/asi/")
        TMCVInternalOrderInsertOrUpdateInput tmcvInternalOrderInsertOrUpdateInput
    );
}
